spring:
  datasource:
    url: jdbc:postgresql://localhost:32768/testing_db
    username: testing_app
    password: password
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false